### ISSUE TITLE
2021实战攻防企业红蓝对抗实践指南-长亭科技出品无法下载

### ISSUE THREAD

**Issue by elleys** [Mr-xn/RedTeam_BlueTeam_HW#1]
文件太大，超Git-LFS 只提供 1 GB 存储空间，和每月 1 GB 的流量
建议改用其他网盘

**Comment by Mr-xn** [comment]
> 文件太大，超Git-LFS 只提供 1 GB 存储空间，和每月 1 GB 的流量
> 建议改用其他网盘

改天弄下
