### ISSUE TITLE
backdoor code may exist

### ISSUE THREAD

**Issue by Make-Ye** [Mr-xn/RedTeam_BlueTeam_HW#6]
ThinkphpGUI-1.3-SNAPSHOT.jar backdoor code Adwind  may exist

**Comment by Mr-xn** [comment]
> ThinkphpGUI-1.3-SNAPSHOT.jar backdoor code Adwind may exist

Thanks your issues. origin repo here: https://github.com/Lotus6/ThinkphpGUI 

this file found nothing about Adwind backdoor  in my option,if u have any details code analysis welcome to report more.

anyway, thanks for the feedback.
